In [1]:
import numpy as np

def print_matrix(matrix, step, row_op=None):
    print(f"Step {step}:")
    if row_op:
        print(f"Operation: {row_op}")
    print(np.array(matrix))
    print()

def gauss_elimination(matrix):
    matrix = np.array(matrix, dtype=float)  # Convert the matrix to a NumPy array
    n = len(matrix)
    step = 0

    # Forward elimination
    for i in range(n):
        # Partial pivoting
        max_row = i + np.argmax(np.abs(matrix[i:, i]))
        if max_row != i:
            matrix[[i, max_row]] = matrix[[max_row, i]]
            step += 1
            print_matrix(matrix, step, f"R{i+1} <-> R{max_row+1}")

        # Make all rows below this one 0 in the current column
        for j in range(i + 1, n):
            factor = matrix[j][i] / matrix[i][i]
            matrix[j, i:] -= factor * matrix[i, i:]
            step += 1
            print_matrix(matrix, step, f"R{j+1} -> R{j+1} - ({factor:.2f})*R{i+1}")

    # Back substitution
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = matrix[i][n] / matrix[i][i]
        for j in range(i - 1, -1, -1):
            matrix[j][n] -= matrix[j][i] * x[i]
        step += 1
        print_matrix(matrix, step, f"Back Substitution for x{i+1}")

    return x

# Example usage
matrix = [
    [1, 2, -1, 1],    # 2x - y + z = 8
    [-3, -1, 2, 3],  # -3x - y + 2z = -11
    [-2, 1, 2, -3]     # -2x + y + 2z = -3
]

solution = gauss_elimination(matrix)
print("Solution:")
print(solution)


Step 1:
Operation: R1 <-> R2
[[-3. -1.  2.  3.]
 [ 1.  2. -1.  1.]
 [-2.  1.  2. -3.]]

Step 2:
Operation: R2 -> R2 - (-0.33)*R1
[[-3.         -1.          2.          3.        ]
 [ 0.          1.66666667 -0.33333333  2.        ]
 [-2.          1.          2.         -3.        ]]

Step 3:
Operation: R3 -> R3 - (0.67)*R1
[[-3.         -1.          2.          3.        ]
 [ 0.          1.66666667 -0.33333333  2.        ]
 [ 0.          1.66666667  0.66666667 -5.        ]]

Step 4:
Operation: R3 -> R3 - (1.00)*R2
[[-3.         -1.          2.          3.        ]
 [ 0.          1.66666667 -0.33333333  2.        ]
 [ 0.          0.          1.         -7.        ]]

Step 5:
Operation: Back Substitution for x3
[[-3.         -1.          2.         17.        ]
 [ 0.          1.66666667 -0.33333333 -0.33333333]
 [ 0.          0.          1.         -7.        ]]

Step 6:
Operation: Back Substitution for x2
[[-3.         -1.          2.         16.8       ]
 [ 0.          1.66666667 -0.333